render-backend:
	helm template ./backend | yh
upgrade-backend:
	helm upgrade backend-v1 ./backend

render-frontend:
	helm template ./frontend | yh
upgrade-frontend:
	helm upgrade frontend-v1 ./frontend
